# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_of_tasks', '0002_auto_20171009_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='published_date',
        ),
        migrations.AddField(
            model_name='task',
            name='last_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.CharField(choices=[('new', 'Новая задача'), ('in_process', 'В процессе'), ('completed', 'Завершена')], default='new', max_length=20),
        ),
    ]
