# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_of_tasks', '0003_auto_20171010_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='status',
        ),
    ]
