# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_of_tasks', '0004_auto_20171010_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая задача'), ('in_process', 'В процессе'), ('completed', 'Завершена')], max_length=20),
        ),
    ]
