# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 09:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_of_tasks', '0008_auto_20171121_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Название статуса')),
                ('ended', models.BooleanField(verbose_name='Закрывает ли статус задачу?')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='new_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='new_status',
            field=models.CharField(blank=True, choices=[('new', 'Новая задача'), ('in_process', 'В процессе'), ('completed', 'Завершена')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='old_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='old_status',
            field=models.CharField(blank=True, choices=[('new', 'Новая задача'), ('in_process', 'В процессе'), ('completed', 'Завершена')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status_n',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='assignment_of_tasks.Statuses'),
            preserve_default=False,
        ),
    ]
