# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_of_tasks', '0010_auto_20171123_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuses',
            options={'verbose_name': 'statuses', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.RenameField(
            model_name='statuses',
            old_name='status',
            new_name='title',
        ),
    ]
