# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_of_tasks', '0011_auto_20171123_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuses',
            name='sort',
            field=models.IntegerField(default=100, verbose_name='Вес для сортировки'),
        ),
    ]
