# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 12:45
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_of_tasks', '0012_statuses_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_changed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_assigned_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Переназначили с')),
                ('new_assigned_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Переназначили на')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Статус изменился с')),
                ('new_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Статус изменился на')),
                ('old_percent', models.IntegerField(blank=True, null=True, verbose_name='Процент выполнения изменен с')),
                ('new_percent', models.IntegerField(blank=True, null=True, verbose_name='Процент выполнения изменен на')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'История',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='statuses',
            options={'ordering': ['sort'], 'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='new_assigned_to',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='new_status',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='old_assigned_to',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='old_status',
        ),
        migrations.AddField(
            model_name='task',
            name='percent',
            field=models.IntegerField(choices=[(0, 0), (10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)], default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Процент выполнения'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='change_state',
            field=models.BooleanField(verbose_name='Изменение параметров задачи'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='assignment_of_tasks.Task', verbose_name='Комментарий к задаче:'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to=settings.AUTH_USER_MODEL, verbose_name='Назначена'),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последней активности'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_of_tasks.Statuses', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='comment',
            name='change_values',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assignment_of_tasks.History_changed', verbose_name='Какие изменения сделал этот комментарий'),
        ),
    ]
